version: "3.7"

services: 
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: .
  #   container_name: rentx
  #   links: 
  #     - database_ignite
  #   depends_on:
  #     - database_ignite

  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
    
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  pgdata: 
    driver: local
  